#!/bin/bash
# Copyright 2023 The MaxMQ Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

# Update copyright year
CURRENT_YEAR=$(date +%Y)

for i in $(git diff --name-only --cached); do
	perl -pi -e "s/(?<=Copyright\ )(?<!$CURRENT_YEAR)\d{4}/$CURRENT_YEAR/g" "$i";
done

# Inspect source code
make inspect
