#!/bin/bash
# Copyright 2023 The MaxMQ Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e

# Colors
CYAN="$(tput -Txterm setaf 6)"
WHITE="$(tput -Txterm setaf 7)"
RESET='\033[0m'
BOLD='\033[0;1m'

function print_task_info() {
	printf "${CYAN}==>${BOLD} %s...${RESET}\n" "$1"
}
function print_task_info_result() {
	printf "${CYAN}==> %s... %s${RESET}\n" "$1" "$2"
}

# Update copyright year
print_task_info "Updating copyright year"
CURRENT_YEAR=$(date +%Y)
for i in $(git diff --name-only --cached); do
	printf "${WHITE}    Updating '%s'${RESET}\n" "$i"
	perl -pi -e "s/(?<=Copyright\ \d{4})(?<!$CURRENT_YEAR)(-\d{4})?/-$CURRENT_YEAR/g" "$i";
done
print_task_info_result "Updating copyright year" "done"

# Inspect source code
make inspect
