# Copyright 2022 The MaxMQ Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

image:
  # MaxMQ Image name
  repository: maxmq
  # The image pull policy
  pullPolicy: IfNotPresent
  # The image tag
  tag: ""
  # The image pull secrets
  pullSecrets: []

# Override the name of the chart
nameOverride: ""
# Override the full name of the chart
fullnameOverride: ""

service:
  # Kubernetes Service type
  type: ClusterIP
  # Port for MQTT
  mqtt: 1883
  # Service annotations
  annotations: { }

# MaxMQ configuration stored in /etc/maxmq.conf
maxmqConfig: {}

podAnnotations: {}
podSecurityContext: {}
securityContext: {}
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
