name: build
on:
  push:
    branches: [ develop, master ]
  pull_request:

env:
  FORCE_COLOR: true

jobs:
  gitlint:
    name: Gitlint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install gitlint
        run: |
          pip install gitlint
          gitlint --version

      - name: Run gitlint
        run: gitlint

  vet:
    name: Vet
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5'

      - name: Run vet target
        run: make vet

  lint:
    name: Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2

  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5'

      - name: Build application
        run: make build

  unit:
    name: Unit Test
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5'

      - name: Run unit tests
        run: make unit
