name: build
on:
  push:
    branches: [ develop, master ]
  pull_request:

env:
  FORCE_COLOR: true

jobs:
  gitlint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install gitlint
        run: |
          pip install gitlint
          gitlint --version

      - name: Run gitlint
        run: gitlint

  vet:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5'

      - name: Run vet target
        run: make vet

  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2

  complexity:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5'

      - name: Install gocyclo
        run: go install github.com/fzipp/gocyclo/cmd/gocyclo@latest

      - name: Calculate cyclomatic complexities
        run: make complexity

  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5'

      - name: Build application
        run: make build

  test:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17.5'

      - name: Run tests
        run: make test
